# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pl_dVWWau9cGwmfFyLeRApoYAOw1FWit
"""

# Titanic Dataset - Exploratory Data Analysis (EDA)
# Task 5: Extract insights using visual and statistical exploration

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Set style for better visualizations
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

print("="*70)
print("TITANIC DATASET - EXPLORATORY DATA ANALYSIS")
print("="*70)

# ============================================================================
# 1. LOAD DATASET
# ============================================================================
print("\n1. LOADING DATASET...")
df = sns.load_dataset('titanic')
print("✓ Dataset loaded successfully!")

# ============================================================================
# 2. INITIAL DATA EXPLORATION
# ============================================================================
print("\n2. INITIAL DATA EXPLORATION")
print("-"*70)

print("\n2.1 First 5 rows:")
print(df.head())

print("\n2.2 Dataset Shape:")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\n2.3 Dataset Information:")
print(df.info())

print("\n2.4 Column Names:")
print(df.columns.tolist())

# ============================================================================
# 3. STATISTICAL SUMMARY
# ============================================================================
print("\n3. STATISTICAL SUMMARY")
print("-"*70)
print(df.describe())

print("\nDescriptive statistics for categorical variables:")
print(df.describe(include='object'))

# ============================================================================
# 4. MISSING VALUES ANALYSIS
# ============================================================================
print("\n4. MISSING VALUES ANALYSIS")
print("-"*70)

missing_values = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing_Count': missing_values,
    'Percentage': missing_percent
})
missing_df = missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False)

print("\nMissing Values Summary:")
print(missing_df)

# Visualize missing values
plt.figure(figsize=(10, 6))
missing_df['Percentage'].plot(kind='barh', color='coral')
plt.xlabel('Percentage Missing (%)')
plt.title('Missing Values by Column')
plt.tight_layout()
plt.savefig('missing_values.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# 5. VALUE COUNTS FOR CATEGORICAL VARIABLES
# ============================================================================
print("\n5. VALUE COUNTS - CATEGORICAL VARIABLES")
print("-"*70)

categorical_cols = ['survived', 'pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

for col in ['survived', 'pclass', 'sex', 'embarked']:
    if col in df.columns:
        print(f"\n{col.upper()} - Value Counts:")
        print(df[col].value_counts())
        print(f"Percentage Distribution:")
        print(df[col].value_counts(normalize=True) * 100)

# ============================================================================
# 6. UNIVARIATE ANALYSIS - VISUALIZATIONS
# ============================================================================
print("\n6. UNIVARIATE ANALYSIS")
print("-"*70)

# 6.1 Survival Rate
plt.figure(figsize=(8, 5))
survival_counts = df['survived'].value_counts()
plt.pie(survival_counts, labels=['Died', 'Survived'], autopct='%1.1f%%', colors=['#ff6b6b', '#51cf66'], startangle=90)
plt.title('Survival Rate Distribution', fontsize=14, fontweight='bold')
plt.savefig('survival_rate.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"\n✓ Survival Rate: {(df['survived'].sum() / len(df)) * 100:.2f}%")

# 6.2 Age Distribution
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.hist(df['age'].dropna(), bins=30, color='skyblue', edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution (Histogram)')

plt.subplot(1, 2, 2)
plt.boxplot(df['age'].dropna(), vert=True)
plt.ylabel('Age')
plt.title('Age Distribution (Boxplot)')

plt.tight_layout()
plt.savefig('age_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# 6.3 Fare Distribution
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.hist(df['fare'].dropna(), bins=30, color='lightcoral', edgecolor='black')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.title('Fare Distribution (Histogram)')

plt.subplot(1, 2, 2)
plt.boxplot(df['fare'].dropna(), vert=True)
plt.ylabel('Fare')
plt.title('Fare Distribution (Boxplot)')

plt.tight_layout()
plt.savefig('fare_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# 6.4 Passenger Class Distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='pclass', palette='viridis')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.title('Passenger Class Distribution')
plt.savefig('class_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# 6.5 Gender Distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='sex', palette='Set2')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Gender Distribution')
plt.savefig('gender_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# 7. BIVARIATE ANALYSIS
# ============================================================================
print("\n7. BIVARIATE ANALYSIS")
print("-"*70)

# 7.1 Survival by Gender
plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='sex', hue='survived', palette='Set1')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Survival Rate by Gender')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.savefig('survival_by_gender.png', dpi=300, bbox_inches='tight')
plt.show()

survival_by_gender = df.groupby('sex')['survived'].mean() * 100
print("\nSurvival Rate by Gender:")
print(survival_by_gender)

# 7.2 Survival by Passenger Class
plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='pclass', hue='survived', palette='coolwarm')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.title('Survival Rate by Passenger Class')
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.savefig('survival_by_class.png', dpi=300, bbox_inches='tight')
plt.show()

survival_by_class = df.groupby('pclass')['survived'].mean() * 100
print("\nSurvival Rate by Class:")
print(survival_by_class)

# 7.3 Age vs Survival
plt.figure(figsize=(10, 5))
sns.violinplot(data=df, x='survived', y='age', palette='muted')
plt.xlabel('Survived')
plt.ylabel('Age')
plt.title('Age Distribution by Survival Status')
plt.xticks([0, 1], ['Died', 'Survived'])
plt.savefig('age_vs_survival.png', dpi=300, bbox_inches='tight')
plt.show()

# 7.4 Fare vs Survival
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x='survived', y='fare', palette='pastel')
plt.xlabel('Survived')
plt.ylabel('Fare')
plt.title('Fare Distribution by Survival Status')
plt.xticks([0, 1], ['Died', 'Survived'])
plt.ylim(0, 300)  # Limit y-axis for better visualization
plt.savefig('fare_vs_survival.png', dpi=300, bbox_inches='tight')
plt.show()

# 7.5 Age vs Fare Scatter Plot
plt.figure(figsize=(10, 6))
scatter = plt.scatter(df['age'], df['fare'], c=df['survived'], cmap='RdYlGn', alpha=0.6, edgecolors='black')
plt.xlabel('Age')
plt.ylabel('Fare')
plt.title('Age vs Fare (colored by Survival)')
plt.colorbar(scatter, label='Survived')
plt.savefig('age_vs_fare_scatter.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# 8. MULTIVARIATE ANALYSIS
# ============================================================================
print("\n8. MULTIVARIATE ANALYSIS")
print("-"*70)

# 8.1 Correlation Heatmap
plt.figure(figsize=(10, 8))
numeric_cols = df.select_dtypes(include=[np.number]).columns
correlation_matrix = df[numeric_cols].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0, fmt='.2f', linewidths=1)
plt.title('Correlation Matrix - Numerical Variables', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('correlation_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nTop Correlations with Survival:")
survival_corr = correlation_matrix['survived'].sort_values(ascending=False)
print(survival_corr)

# 8.2 Pair Plot (selected variables)
print("\n✓ Generating pair plot (this may take a moment)...")
selected_cols = ['survived', 'pclass', 'age', 'fare', 'sibsp']
pairplot = sns.pairplot(df[selected_cols].dropna(), hue='survived', palette='Set1', diag_kind='kde')
pairplot.fig.suptitle('Pair Plot - Key Variables', y=1.02, fontsize=14, fontweight='bold')
plt.savefig('pairplot.png', dpi=300, bbox_inches='tight')
plt.show()

# 8.3 Survival by Class and Gender
plt.figure(figsize=(10, 6))
sns.catplot(data=df, x='pclass', hue='survived', col='sex', kind='count', palette='Set2', height=5, aspect=0.8)
plt.savefig('survival_class_gender.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# 9. KEY INSIGHTS & FINDINGS
# ============================================================================
print("\n9. KEY INSIGHTS & FINDINGS")
print("="*70)

# Calculate key statistics
total_passengers = len(df)
survival_rate = (df['survived'].sum() / total_passengers) * 100
female_survival = df[df['sex'] == 'female']['survived'].mean() * 100
male_survival = df[df['sex'] == 'male']['survived'].mean() * 100
class1_survival = df[df['pclass'] == 1]['survived'].mean() * 100
class3_survival = df[df['pclass'] == 3]['survived'].mean() * 100
avg_age = df['age'].mean()
avg_fare = df['fare'].mean()

print(f"""
KEY FINDINGS:

1. SURVIVAL STATISTICS:
   • Overall Survival Rate: {survival_rate:.2f}%
   • Female Survival Rate: {female_survival:.2f}%
   • Male Survival Rate: {male_survival:.2f}%
   → Females had {female_survival - male_survival:.2f}% higher survival rate

2. CLASS IMPACT:
   • First Class Survival: {class1_survival:.2f}%
   • Third Class Survival: {class3_survival:.2f}%
   → First class passengers had {class1_survival - class3_survival:.2f}% higher survival rate

3. DEMOGRAPHICS:
   • Average Age: {avg_age:.2f} years
   • Average Fare: ${avg_fare:.2f}
   • Total Passengers: {total_passengers}

4. MISSING DATA:
   • Age: {df['age'].isnull().sum()} missing values ({(df['age'].isnull().sum()/total_passengers)*100:.1f}%)
   • Cabin: {df['deck'].isnull().sum()} missing values ({(df['deck'].isnull().sum()/total_passengers)*100:.1f}%)
   • Embarked: {df['embarked'].isnull().sum()} missing values

5. CORRELATIONS:
   • Strongest positive correlation with survival: Fare ({correlation_matrix.loc['survived', 'fare']:.3f})
   • Strongest negative correlation with survival: Pclass ({correlation_matrix.loc['survived', 'pclass']:.3f})

CONCLUSIONS:
✓ Gender and class were the strongest predictors of survival
✓ Women and children had priority in lifeboats ("women and children first" policy)
✓ Higher class passengers had better access to lifeboats
✓ Higher fares (luxury cabins) correlated with better survival rates
""")

print("\n" + "="*70)
print("EDA COMPLETED SUCCESSFULLY!")
print("All visualizations have been saved as PNG files.")
print("="*70)

from google.colab import files

files.download('missing_values.png')

"""You can replace `'missing_values.png'` with any other file name you wish to download (e.g., `'survival_rate.png'`, `'correlation_heatmap.png'`, etc.). This will prompt your browser to download the file to your default downloads location, from where you can move it to your desktop."""